#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
killall -9 xsettingsd sxhkd dunst ksuperkey

xsettingsd &
sxhkd &
nm-applet &

#launcher polybar
$HOME/.config/bspwm/polybar/launch.sh

#wallpaper
feh --bg-fill ~/.config/bspwm/wallpaper/wall.png

#compositor
picom &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer true

#floating windows
bspc rule -a Thunar state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on

bash $HOME/.fehbg

ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &
